// Regenerates js/vocab-data.js from the chapter JSON files.
// Run from the project root:  node tools/build-vocab.js
//
// The vocab JSON is baked into a JS file (window.VOCAB_DATA) so the site
// also works when opened directly from the filesystem (file://), where
// fetch() of local JSON files is blocked by browsers.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const VOCAB_DIR = path.join(ROOT, 'vocab');
const CHAPTER_FILES = fs.readdirSync(VOCAB_DIR).filter((f) => f.endsWith('.json')).sort();

function main() {
  let all = [];
  for (const file of CHAPTER_FILES) {
    const cards = JSON.parse(fs.readFileSync(path.join(VOCAB_DIR, file), 'utf8'));
    console.log(`${file}: ${cards.length} cards`);
    all = all.concat(cards);
  }

  // Sanity check: note_id must be unique across all chapters.
  const seen = new Set();
  for (const card of all) {
    if (seen.has(card.note_id)) {
      throw new Error(`Duplicate note_id: ${card.note_id}`);
    }
    seen.add(card.note_id);
  }

  const out =
    '// GENERATED by tools/build-vocab.js - do not edit by hand.\n' +
    '// Source: the JSON files in vocab/.\n' +
    'window.VOCAB_DATA = ' + JSON.stringify(all) + ';\n';

  const outDir = path.join(ROOT, 'js');
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'vocab-data.js'), out);
  console.log(`Wrote js/vocab-data.js with ${all.length} cards.`);
}

main();
