// Regenerates js/vocab-data.js from the chapter JSON files.
// Run from the project root:  node tools/build-vocab.cjs
//
// The vocab JSON is LZ-String compressed into a JS file (window.VOCAB_DATA)
// so the site works when opened directly from the filesystem (file://),
// where fetch() of local JSON files is blocked by browsers.

const fs = require('fs');
const path = require('path');
const LZString = require('lz-string');

const ROOT = path.join(__dirname, '..');
const VOCAB_DIR = path.join(ROOT, 'vocab');
const CHAPTER_FILES = fs.readdirSync(VOCAB_DIR).filter((f) => f.endsWith('.json')).sort();

function main() {
  let all = [];
  for (const file of CHAPTER_FILES) {
    const cards = JSON.parse(fs.readFileSync(path.join(VOCAB_DIR, file), 'utf8'));
    console.log(`${file}: ${cards.length} cards`);
    all = all.concat(cards);
  }

  // Deduplicate: skip cards with duplicate note_id, keep the first occurrence.
  const seen = new Set();
  const deduped = [];
  for (const card of all) {
    if (seen.has(card.note_id)) {
      console.warn(`Skipped duplicate note_id: ${card.note_id} (${card.character || card.word || card.keyword})`);
    } else {
      seen.add(card.note_id);
      deduped.push(card);
    }
  }
  all = deduped;

  const raw = JSON.stringify(all);
  const compressed = LZString.compressToBase64(raw);
  const out =
    '// GENERATED by tools/build-vocab.cjs - do not edit by hand.\n' +
    '// Source: the JSON files in vocab/.\n' +
    '// LZ-String compressed — requires js/vendor/lz-string.min.js to be loaded first.\n' +
    'window.VOCAB_DATA = JSON.parse(LZString.decompressFromBase64("' + compressed + '"));\n';

  const outDir = path.join(ROOT, 'js');
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'vocab-data.js'), out);
  const pct = ((1 - compressed.length / raw.length) * 100).toFixed(1);
  console.log(`Wrote js/vocab-data.js with ${all.length} cards (${compressed.length} chars, ${pct}% smaller than raw JSON).`);
}

main();
